name: Python CI

on:
  push:
    paths:
      - 'projects/python-authlog-bruteforce-detector/**'
      - '.github/workflows/python-ci.yml'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r projects/python-authlog-bruteforce-detector/requirements.txt
      - name: Lint
        run: |
          pip install flake8
          flake8 projects/python-authlog-bruteforce-detector/scripts
      - name: Run tests
        run: |
          pip install pytest
          pytest -q
